version = "0.0.4"
author = "disruptek"
description = "nim package handler from the future"
license = "MIT"
requires "nim >= 1.1.1"
requires "compiler >= 1.1.1"
requires "https://github.com/disruptek/github.git#1.0.0"
requires "cligen >= 0.9.41"
requires "bump >= 1.8.11"
requires "nimgit2 >= 0.1.0"
requires "npeg"
requires "parsetoml"
requires "https://github.com/disruptek/cutelog.git >= 1.0.0"
requires "https://github.com/stefantalpalaru/nim-unittest2.git >= 0.0.1"

srcDir = "src"
