version = "0.0.41"
author = "disruptek"
description = "nim package handler from the future"
license = "MIT"
requires "nim >= 1.0.4"
requires "compiler >= 1.0.4"
requires "github >= 1.0.2"
requires "cligen >= 0.9.41"
requires "bump >= 1.8.12"
requires "nimgit2 >= 0.1.1"
requires "npeg >= 0.21.3"
requires "https://github.com/disruptek/cutelog#1.1.1"
requires "https://github.com/stefantalpalaru/nim-unittest2 >= 0.0.1"

bin = @["nimph"]
srcDir = "src"
